name: Notify Discord on Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
            -d '{
              "content": "New commit pushed to repository!",
              "embeds": [
                {
                  "title": "Commit in Repository",
                  "description": "A new commit has been pushed to the repository.",
                  "url": "${{ github.event.head_commit.url }}",
                  "color": 65280,
                  "fields": [
                    {
                      "name": "Repository",
                      "value": "${{ github.repository }}",
                      "inline": true
                    },
                    {
                      "name": "Branch",
                      "value": "${{ github.ref_name }}",
                      "inline": true
                    },
                    {
                      "name": "Commit Message",
                      "value": "${{ github.event.head_commit.message }}"
                    },
                    {
                      "name": "Author",
                      "value": "${{ github.event.head_commit.author.name }}",
                      "inline": true
                    }
                  ]
                }
              ]
            }' \
            $DISCORD_WEBHOOK_URL
